### PR TITLE
plasma-workspace 5.5.0-5 with patch for bug355684 in xembedsniproxy

### PR DESCRIPTION
**Pull request by FadeMind**
# Review
## xembedsniproxy issue
https://forum.manjaro.org/index.php?topic=29006.msg241450#msg241450
https://bugs.kde.org/show_bug.cgi?id=355684

On my setup in default plasma tray freak out and don't render tray icons anyway (instead of icon I saw blank reserved space).
This issue is in xembedsniproxy app (for legacy icons), patch fixing this issue and was accepted by developer.
## Disable debug msgs from KDE Apps
https://git.reviewboard.kde.org/r/121903/diff/1?file=338977#file338977line12
https://bbs.archlinux.org/viewtopic.php?id=193123

In default KDE print lots of stdout msgs in to journal. For normal users (with SSD) this is useless and take writes.
Patch just disable output debug info via set global environment (taken from `startkde` bashscript.)
@Kirek @oberon2007 @philmmanjaro 

Regards

Tomasz

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Please remove the **355684** patch file and add the url for downloading it: https://bugsfiles.kde.org/attachment.cgi?id=95921. Also the revision should be **4.1** and not **5**.

**Comment by Kirek** [comment]
I'm okay with adding xembedsniproxy patch, but not disabling the debug messages, there is an open issue in the kde reviewboard and they never merged it.

**Comment by Kirek** [comment]
https://git.reviewboard.kde.org/r/121903/#comment51110

**Comment by philmmanjaro** [comment]
I agree with @Kirek here. Please drop the debug-msgs patch and lower the revision.

**Comment by FadeMind** [comment]
@philmmanjaro  @Kirek  ready

**Pull request merged**
