### PR TITLE
Firmware  for BCM20702A1 and QCA9565 BT devices

### PR DESCRIPTION
**Pull request by FadeMind**
Adding firmware for:
- Qualcomm Atheros QCA9565 bluetooth chipset based devices
- BCM20702A1 bluetooth chipset based devices

Expand comments. 
Tested localy, all is fine.

@philmmanjaro

### CODE REVIEW

**Comment by coffeeking** [comment]
hi
This is awesome. What package is this contained in so I can add it to 
sonar images?
Thanks
Kendell clark

**Comment by FadeMind** [comment]
@coffeeking `bcm20702a1-firmware` and `qca9565-bluetooth-firmware` from AUR.

**Comment by coffeeking** [comment]
hi
I cannot add aur packages to built images. Any chance these firmware 
files can be rolled into either linux-firmware upstream or manjaro-firmware?
Thanks
Kendell clark

**Comment by philmmanjaro** [comment]
Install **manjaro-firmware** and you're fine. We included those AUR packages in it.

**Comment by coffeeking** [comment]
oops, my bad. Just added to sonar images.

**Pull request merged**
