### PR TITLE
plymouth, kinfocenter(about distro) artwork refresh

### PR DESCRIPTION
**Pull request by Tids**
Because of the Manjaro logo change I've added the new "standard"-artwork-shapes to plymouth (Its mostly a little size-change for the text "manjaro"). However I've also re-created the password field. Because the old one really looks out of place for manjaros overall style. I hope thats OK.

++ also replaced the distro icon in the kinfocenter with the new one.

### CODE REVIEW

**Comment by oberon2007** [comment]
Thank you, @Tids ! I have since changed the PKGBUILD for **kinfocenter** to use the **manjaro-icons** package.
Could you just revert https://github.com/manjaro/packages-extra/pull/100/commits/f53f2b3d47e2197bb50d9d0218cc00821369578a so we can merge the plymouth adjustments?

**Comment by Tids** [comment]
Lets hope i've done the right thing now... i've never done a revert before 🙈

**Comment by oberon2007** [comment]
Looking good : smile: 👍

**Comment by oberon2007** [comment]
btw, @Ste74 @philmmanjaro Is there a reason why **plymouth** pkg is still stuck at **v0.8.8**? Or should we update it to **v0.9.2** meanwhile? Just want to make sure I'm not missing anything here ... :wink:

**Comment by philmmanjaro** [comment]
We have two packages:

```
extra/plymouth 1:0.8.8-2 [Installiert]
    A graphical boot splash screen with kernel mode-setting support
extra/plymouth-dev 0.9.2.r44.g375a65f-1
    A graphical boot splash screen with kernel mode-setting support (development
    version)
```
You can try the dev-package and see yourself why we are still "stuck" on the old one :smile:

**Comment by oberon2007** [comment]
:yum: I'm not using plymouth currently myself - are there known issues with the git version? @Ste74 you have played with this some more a while ago, haven't you?

**Pull request merged**
