### PR TITLE
Update for Nvidia 384.59 long-lived release

### PR DESCRIPTION
**Pull request by jonathonf**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Due to heat problems we will stay on **v375** series for a while. This is also long-lived.

**Comment by jonathonf** [comment]
What heat problems?

**Comment by philmmanjaro** [comment]
Well, beside heat problems on some hardware this new driver series produces a lot of [bugs](https://devtalk.nvidia.com/search/more/sitecommentsearch/384/?boards=98&order=relevance). I recommend to wait at least for a newer revision and stay on **v375** a little longer.

**Comment by jonathonf** [comment]
> heat problems on some hardware

Are these down to the drivers or the hardware itself? From the threads I've read the heat issues are on new cards (1080 etc.) which are running overclocked or e.g. with third-party coolers.

> a lot of bugs

The majority of those threads reference 384.47, which was the last beta release. There may still be issues, but 384.59 is a final release with a ton of fixes:

> VDPAU error on some videos
> Fixed. Problem seems to have been resolved after installing 384.59. Thanks! 

> Occasional solid color flashing/flickering with GTX970 on 384.47
> I was having the issue before, and I haven't seen the issue happen since upgrading to 384.59.

However - if you want to wait for a while yet that's understandable. Anyone who really wants the newer driver can build the packages themselves. :) https://forum.manjaro.org/t/building-your-own-nvidia-extramodule/28597

**Pull request closed without merging**
