### PR TITLE
remove Catalyst support for GCN(RadeonSI supported) hardware in mhwd

### PR DESCRIPTION
**Pull request by Tids**
For GraphicsCoreNext(GCN) generations the "Radeon" kernel driver is the best choice when it comes to stability and features. The Mesa OpenGL library (radeonSI) is also much faster than fglrx.

Pro

- Working KMS
- Working TTY Switch
- Faster OpenGL
- Xorg>=1.8 support
- Wayland support

Con

- No OpenCL support

Because of this, i think its the best option to remove fglrx from mhwd for users of GCN chips. Things like this: https://forum.manjaro.org/t/how-to-reset-the-display-driver-settings/36729 or broken xorg setups should not happen anymore.

-------------

For older chips its a different story. Lets wait a bit longer to get some more features in: https://www.phoronix.com/scan.php?page=news_item&px=OpenGL-43-Lands-In-R600g

-------------
This would also be "Step 1" for https://github.com/manjaro/release-plan/issues/37

### CODE REVIEW

**Comment by mirh** [comment]
> No OpenCL support

That's actually already/still [achievable](https://aur.archlinux.org/packages/opencl-amd/). Even without us waiting for AMDGPU-PRO to land. 

> For older chips its a different story. Lets wait a bit longer to get some more features in: 

I regret that there instead OpenCL is still a distant mirage. 

---
On the other hand, I'm still left wondering why you don't just make free driver default, except for those fglrx ids.

**Comment by Tids** [comment]
@mirh but we cannot ship the pro-opencl by default, like we do for all the other drivers. However, thanks for this hint! :)

Free drivers are the default drivers. When you install Manjaro today it'll start to load the free drivers on all AMD systems. Fglrx is just a good to use fallback for older AMD cards, until the r600g has reached opengl 4.4 support.

**Comment by mirh** [comment]
> Free drivers are the default drivers.

I know, I didn't mean in that sense. 
Default as in "if it's not among these pre-GCN ids", then offer amdgpu stuff. 
Instead of the current "if it is GCN" - that way you don't have to loose your mind with all the infinite new cards that will be released.

**Comment by philmmanjaro** [comment]
@Tids: I need a little more info on this one. Does this break anything on given hardware? Also this needs a revision bump to be affective.

**Comment by Tids** [comment]
@philmmanjaro  
> Does this break anything on given hardware?

No. The current situation is that we show up catalyst support for all the AMD Hardware that is supported by catalyst (so R600, evergreen, southern island, sea island, arctic island and volcanic island).
While for R600 and evergreen this is a "endurable situation", since they can make use of catalysts OpenGL 4.x and OpenCL 1.2 support, for all the others we have a much faster openGL with Mesa RadeonSI support (and if needed also [OpenCL from the AUR](https://aur.archlinux.org/packages/opencl-amd/) until ROCm is available for all.

So there is no need at all to provide them the dangerous graphicsstack of catalyst.

For users who already run that stack it will not change a thing, It only removes the ability to install it via mhwd/manjaro settings manager for users of "in support" hardware (southern island, sea island, arctic island and volcanic island)

@mirh 
> that way you don't have to loose your mind with all the infinite new cards that will be released.

I wont do. New IDs will not be added to catalyst anymore, so there is no need to add new generations of graphicscards to the "blacklist" block. I'm almost sure that we dont even need to add the polaris generation in there - I've just added them in case of.

**Comment by mirh** [comment]
>  until ROCm is available for all

ROCm will \*never\* be available for all. It requires very recent gpus and cpus. 

> New IDs will not be added to catalyst anymore, so there is no need to add new generations of graphicscards to the "blacklist" block.

Uh? ~~That was exactly my point?~~
Oh, I didn't get this blacklist was being applied in turn back to catalyst "list". 
Feels somehow counterintuitive, but I guess it's good.

**Comment by Tids** [comment]
@mirh 
> ROCm will *never* be available for all. It requires very recent gpus and cpus.

If we're lucky the support will be for all AMDGPU-supported generations. Thats what i wanna say with "for all" - and it's what we need. :)

This weekend i had a very nice talk to a good friend who said that catalyst isnt even worth for OpenCL support, since it was a buggy implementation, that was very crashy compared to the nvidia plattform of openCL and it is only OCL1.2 ready, while many apps nowadays want a minimum of 2.0.

Of course I dont know if thats true. the only OpenCL ready app I've ever used at catalyst time was an audio converter (soundkonverter maybe?) wich has never worked when OpenCL was active 😂

Maybe we should also start a test if it even works for our users.

**Comment by mirh** [comment]
> If we're lucky the support will be for all AMDGPU-supported generations.

No, really, no. 
I gathered some more info [here](https://github.com/grmat/opencl-amd/issues/2#issuecomment-349448374). 
\*Some\* gcn 3rd gen supporting it is already a miracle. 

> This weekend i had a very nice talk to a good friend who said that catalyst isnt even worth for OpenCL support, since it was a buggy implementation

True[[1](https://community.amd.com/thread/221286)][[2](https://github.com/CNugteren/CLBlast/issues/229#issuecomment-354609110)][[3](https://github.com/codeplaysoftware/computecpp-sdk/issues/77#issuecomment-355672039)]
But at least my very anecdotal experience, showed me no bug to be really important or relevant enough to be an actual blocker. 

> that was very crashy compared to the nvidia plattform of openCL 

Compared to _CUDA_, if any - because as far as the legends I heard go, you are almost better doing your calculations in GLSL than opencl on their cards. But I might be wrong on this. 

> and it is only OCL1.2 ready, while many apps nowadays want a minimum of 2.0.

Wrong and wronger. 
Since like half of 2014, it should totally be 2.0. You need at least gcn 2nd gen though. 
(or at least, I had direct confirmations of this in windows)

As for what most apps these days use.. God, absolutely not. 
I swear (for as much as I'd love the very cool 2.0 features to be used) I have still to find \*something\* using it. 

> Maybe we should also start a test if it even works for our users.

Well, here's the plot twist. Turns out what originally was just a "because moar choice" *interest* (you know, like one of those systemD wingnuts - except empathy for others maybe) I found myself eventually trying to do some dumb ML on it. 
I mean, tensorflow (the final aim) still crashes on my humble laptop.. But for as much as we know it may be their fault. 
And at least the other 2-3 conformance suites and "testers" I could find are 100% working. 

---
ALSO, just for the records - last time I checked a couple of months ago, it was still a 20% faster than mesa (in cs:go at least). But this is another matter.

**Comment by Tids** [comment]
> Since like half of 2014, it should totally be 2.0. You need at least gcn 2nd gen though.

On the hardware side (I think all the GCN generations should be able to handle OpenCL 2.x), but was catalyst (linux) also providing OCL 2.0?

> And at least the other 2-3 conformance suites and "testers" I could find are 100% working.

Important would be things like Blender, Darktable. Realworld apps. Because it's of no use if testing suits work with it, but apps fail, since nobody will ever work on "make it work with catalyst OCL"

-----
I mean in the end catalyst is still available in the repo, it's just not available to install via mhwd for newer hardware, so users who really want to have it need a bit of experience to install it, because they will also need it to uninstall it.

**Comment by mirh** [comment]
Well, seems like _some day_ came faster than I expected. 
I tried `juliagpu`, `mandelgpu`, `smallpt-gpu`, `mandelbulbgpu`, `gimp`,  `clpeak`, `darktable`, `viennacl`, `lulesh-cl`, `xsbench-cl` tests. 

Now, I'm not totally sure if gimp there was using openCL or not, and fglrx cpu device was crashing hard in half of the tests (it might be also responsible of the last two tests not running at all - considering they had no mention of the silicon they were running from) but for the reminder, everything went good. 

I also tested like a hour of good old folding@home (FahCore_21), with no problems to report.

**Pull request merged**
